apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: allow-kong-to-api
  namespace: api
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: kong
  to:
    - group: ""
      kind: Service
